-- SALON BOOKING: TABLES, RLS, VALIDATION, AND APPLICATION RPCS
-- Generated by: node scripts/export-supabase-schema.mjs
-- FRESH SUPABASE PROJECT ONLY. Run once as the owner in the SQL Editor.
-- Do NOT run alongside the numbered migrations or over an existing salon schema.
-- For existing projects, apply only unapplied files from supabase/migrations/.
-- Supabase must already provide auth.users, auth.uid(), anon, authenticated.
-- No credentials, admin accounts, or sample customer/service data are seeded.
-- The salon timezone defaults to UTC; configure the real zone before launch.
-- After setup, provision a Supabase Auth user and add its UUID to
-- private.salon_admins as the owner. See README.md for configuration and tests.
-- SQL runtime validation has not been performed in the Android workspace.

begin;

do $preflight$
begin
  if pg_catalog.to_regclass('public.services') is not null
     or pg_catalog.to_regclass('public.bookings') is not null
     or pg_catalog.to_regtype('public.booking_status') is not null
     or pg_catalog.to_regclass('private.salon_booking_settings') is not null
     or pg_catalog.to_regclass('private.salon_admins') is not null then
    raise exception using errcode = '42P07',
      message = 'Salon objects already exist. Use only unapplied numbered migrations, not the fresh-project SQL bundle.';
  end if;
end;
$preflight$;

-- Source: supabase/migrations/20261005000000_create_services_and_bookings.sql
create type public.booking_status as enum (
  'pending',
  'confirmed',
  'completed',
  'cancelled'
);

create table public.services (
  id uuid primary key default gen_random_uuid(),
  name text not null constraint services_name_not_blank check (btrim(name) <> ''),
  duration integer not null constraint services_duration_positive check (duration > 0),
  price numeric(10, 2) not null constraint services_price_nonnegative
    check (price >= 0 and price <> 'NaN'::numeric)
);

comment on column public.services.duration is 'Service duration in whole minutes.';
comment on column public.services.price is 'Amount in the salon currency, not minor units (cents).';

create table public.bookings (
  id uuid primary key default gen_random_uuid(),
  customer_name text not null constraint bookings_customer_name_not_blank
    check (btrim(customer_name) <> ''),
  phone text not null constraint bookings_phone_not_blank check (btrim(phone) <> ''),
  service_id uuid not null constraint bookings_service_id_fkey
    references public.services (id) on delete restrict,
  slot_time timestamptz not null,
  status public.booking_status not null default 'pending'
);

comment on column public.bookings.phone is 'Text preserves country codes, formatting, and leading zeros.';
comment on column public.bookings.slot_time is 'Appointment start instant; submit a timestamp with a timezone offset.';

create index bookings_service_id_idx on public.bookings (service_id);
create index bookings_slot_time_idx on public.bookings (slot_time);

alter table public.services enable row level security;
alter table public.bookings enable row level security;

-- Supabase may grant default table privileges to its API roles. Start with
-- explicit least-privilege access so customer contact data remains private.
revoke all privileges on table public.services, public.bookings from public, anon, authenticated;
grant select on table public.services to anon, authenticated;

create policy "Services are publicly readable"
  on public.services
  for select
  to anon, authenticated
  using (true);

-- No booking policies or client write grants yet. Authenticated customer/admin
-- access needs an ownership model in Phase 2, not a blanket public policy.

-- Source: supabase/migrations/20261005010000_add_guest_booking_rpcs.sql
create schema if not exists private;
revoke all on schema private from public, anon, authenticated;

create table private.salon_booking_settings (
  singleton boolean primary key default true check (singleton),
  time_zone text not null default 'UTC'
);
alter table private.salon_booking_settings enable row level security;
revoke all on table private.salon_booking_settings from public, anon, authenticated;

comment on column private.salon_booking_settings.time_zone is
  'Editable IANA salon timezone. UTC is a configuration default, not an inferred salon location. Set this before accepting bookings.';

create function private.validate_salon_booking_settings()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if new.time_zone is null or not exists (
    select 1 from pg_catalog.pg_timezone_names as zone where zone.name = new.time_zone
  ) then
    raise exception using errcode = '22023', message = 'INVALID_SALON_TIME_ZONE';
  end if;
  return new;
end;
$$;
revoke all on function private.validate_salon_booking_settings() from public, anon, authenticated;

create trigger salon_booking_settings_validate
before insert or update on private.salon_booking_settings
for each row execute function private.validate_salon_booking_settings();

insert into private.salon_booking_settings (singleton, time_zone) values (true, 'UTC');

alter table public.bookings add column end_time timestamptz;
update public.bookings as booking
set end_time = booking.slot_time + pg_catalog.make_interval(mins => service.duration)
from public.services as service
where service.id = booking.service_id;
alter table public.bookings alter column end_time set not null;
alter table public.bookings add constraint bookings_end_after_start check (end_time > slot_time);

comment on column public.bookings.end_time is
  'Duration snapshot at reservation time. Recomputed only when service_id or slot_time changes; later service edits do not move existing appointments.';

create function private.set_booking_end_time()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
  v_duration integer;
begin
  if tg_op = 'INSERT' then
    -- Always derive the snapshot; callers cannot choose a shorter duration.
    select service.duration into v_duration from public.services as service where service.id = new.service_id;
    if not found and new.service_id is not null then
      raise exception using errcode = '23503', message = 'INVALID_SERVICE';
    end if;
    new.end_time := new.slot_time + pg_catalog.make_interval(mins => v_duration);
  elsif new.service_id is distinct from old.service_id or new.slot_time is distinct from old.slot_time then
    select service.duration into v_duration from public.services as service where service.id = new.service_id;
    if not found and new.service_id is not null then
      raise exception using errcode = '23503', message = 'INVALID_SERVICE';
    end if;
    new.end_time := new.slot_time + pg_catalog.make_interval(mins => v_duration);
  elsif new.end_time is distinct from old.end_time then
    raise exception using errcode = '23514', message = 'BOOKING_END_TIME_IS_DERIVED';
  end if;
  return new;
end;
$$;
revoke all on function private.set_booking_end_time() from public, anon, authenticated;

create trigger bookings_set_end_time
before insert or update on public.bookings
for each row execute function private.set_booking_end_time();

-- One shared calendar, including pending and completed appointments. Native
-- range GiST support needs no extension. Existing conflicts abort this entire
-- migration: never delete or silently cancel a customer's reservation.
alter table public.bookings add constraint bookings_no_overlap
exclude using gist (tstzrange(slot_time, end_time, '[)') with &&)
where (status <> 'cancelled'::public.booking_status);

-- Preserve the existing table-level privacy boundary and its lack of policies.
revoke all on table public.bookings from public, anon, authenticated;

create function public.get_booking_config()
returns table (time_zone text, min_date date, max_date date)
language sql
stable
security definer
set search_path = ''
as $$
  select settings.time_zone,
         (pg_catalog.statement_timestamp() at time zone settings.time_zone)::date,
         (pg_catalog.statement_timestamp() at time zone settings.time_zone)::date + 90
  from private.salon_booking_settings as settings
  where settings.singleton;
$$;
revoke all on function public.get_booking_config() from public, anon, authenticated;
grant execute on function public.get_booking_config() to anon, authenticated;

create function public.get_available_slots(p_service_id uuid, p_date date)
returns table (slot_time timestamptz)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_time_zone text;
  v_today date;
  v_duration integer;
  v_now timestamptz := pg_catalog.clock_timestamp();
begin
  select settings.time_zone into strict v_time_zone
  from private.salon_booking_settings as settings where settings.singleton;
  v_today := (v_now at time zone v_time_zone)::date;

  if p_service_id is null or p_date is null or not pg_catalog.isfinite(p_date)
     or p_date < v_today or p_date > v_today + 90 then
    raise exception using errcode = '22023', message = 'INVALID_BOOKING_INPUT';
  end if;

  select service.duration into v_duration from public.services as service where service.id = p_service_id;
  if not found then
    raise exception using errcode = '22023', message = 'INVALID_SERVICE';
  end if;

  return query
  with candidates as (
    select p_date + time '10:00' + step.n * interval '30 minutes' as local_start
    from pg_catalog.generate_series(0, 19) as step(n)
  ), instants as (
    select candidate.local_start, candidate.local_start at time zone v_time_zone as start_at
    from candidates as candidate
  )
  select instant.start_at
  from instants as instant
  where instant.start_at > v_now
    -- Skip nonexistent wall times in timezones with a daytime offset change.
    and (instant.start_at at time zone v_time_zone) = instant.local_start
    and instant.start_at + pg_catalog.make_interval(mins => v_duration)
        <= (p_date + time '20:00') at time zone v_time_zone
    and not exists (
      select 1 from public.bookings as booking
      where booking.status <> 'cancelled'::public.booking_status
        and pg_catalog.tstzrange(booking.slot_time, booking.end_time, '[)')
            && pg_catalog.tstzrange(instant.start_at,
                 instant.start_at + pg_catalog.make_interval(mins => v_duration), '[)')
    )
  order by instant.start_at;
end;
$$;
revoke all on function public.get_available_slots(uuid, date) from public, anon, authenticated;
grant execute on function public.get_available_slots(uuid, date) to anon, authenticated;

create function public.create_booking(
  p_booking_id uuid,
  p_service_id uuid,
  p_slot_time timestamptz,
  p_customer_name text,
  p_phone text
)
returns table (
  id uuid,
  service_id uuid,
  customer_name text,
  phone text,
  slot_time timestamptz,
  end_time timestamptz,
  status public.booking_status
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_name text := pg_catalog.btrim(p_customer_name);
  v_phone text := pg_catalog.btrim(p_phone);
  v_time_zone text;
  v_today date;
  v_local_start timestamp;
  v_duration integer;
  v_end_time timestamptz;
  v_booking public.bookings%rowtype;
begin
  if p_booking_id is null then
    raise exception using errcode = '22023', message = 'INVALID_BOOKING_INPUT';
  end if;

  -- Serialize retries of the same client UUID before looking up a receipt.
  -- Hash collisions only serialize unrelated requests; they never grant access.
  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(p_booking_id::text, 0));
  select booking.* into v_booking from public.bookings as booking where booking.id = p_booking_id for share;
  if found and (v_booking.service_id is distinct from p_service_id
       or v_booking.slot_time is distinct from p_slot_time
       or v_booking.customer_name is distinct from v_name
       or v_booking.phone is distinct from v_phone) then
    raise exception using errcode = '22023', message = 'REQUEST_MISMATCH';
  end if;

  if p_service_id is null or p_slot_time is null
     or not pg_catalog.isfinite(p_slot_time)
     or v_name is null or pg_catalog.char_length(v_name) not between 2 and 100
     or v_name ~ '[[:cntrl:]]'
     or v_phone is null or pg_catalog.char_length(v_phone) > 32
     or v_phone !~ '^[0-9+(). -]+$'
     or pg_catalog.char_length(pg_catalog.regexp_replace(v_phone, '[^0-9]', '', 'g')) not between 7 and 15 then
    raise exception using errcode = '22023', message = 'INVALID_BOOKING_INPUT';
  end if;

  if v_booking.id is not null then
    -- An exact, normalized retry succeeds even after its appointment has passed,
    -- been cancelled, or its service duration/configuration has since changed.
    return query select v_booking.id, v_booking.service_id, v_booking.customer_name,
      v_booking.phone, v_booking.slot_time, v_booking.end_time, v_booking.status;
    return;
  end if;

  -- Keep configuration and duration stable through validation and the insert.
  select settings.time_zone into strict v_time_zone
  from private.salon_booking_settings as settings where settings.singleton for share;
  select service.duration into v_duration
  from public.services as service where service.id = p_service_id for share;
  if not found then
    raise exception using errcode = '22023', message = 'INVALID_SERVICE';
  end if;

  v_today := (pg_catalog.clock_timestamp() at time zone v_time_zone)::date;
  v_local_start := p_slot_time at time zone v_time_zone;
  v_end_time := p_slot_time + pg_catalog.make_interval(mins => v_duration);

  if p_slot_time <= pg_catalog.clock_timestamp() then
    raise exception using errcode = '23P01', message = 'SLOT_UNAVAILABLE';
  end if;
  if v_local_start::date < v_today or v_local_start::date > v_today + 90
     or v_local_start::time < time '10:00' or v_local_start::time > time '19:30'
     or extract(minute from v_local_start) not in (0, 30)
     or extract(second from v_local_start) <> 0
     or (v_local_start at time zone v_time_zone) <> p_slot_time
     or v_end_time > (v_local_start::date + time '20:00') at time zone v_time_zone then
    raise exception using errcode = '22023', message = 'INVALID_BOOKING_INPUT';
  end if;

  if exists (
    select 1 from public.bookings as booking
    where booking.status <> 'cancelled'::public.booking_status
      and pg_catalog.tstzrange(booking.slot_time, booking.end_time, '[)')
          && pg_catalog.tstzrange(p_slot_time, v_end_time, '[)')
  ) then
    raise exception using errcode = '23P01', message = 'SLOT_UNAVAILABLE';
  end if;

  begin
    insert into public.bookings as booking (id, service_id, customer_name, phone, slot_time, status)
    values (p_booking_id, p_service_id, v_name, v_phone, p_slot_time, 'confirmed')
    returning booking.* into v_booking;
  exception
    -- The exclusion constraint, not the earlier availability read, decides
    -- concurrent claims (including different services and different start times).
    when exclusion_violation then
      raise exception using errcode = '23P01', message = 'SLOT_UNAVAILABLE';
    when unique_violation then
      -- Also handle a privileged writer that did not take the advisory lock.
      select booking.* into v_booking from public.bookings as booking where booking.id = p_booking_id;
      if not found or v_booking.service_id is distinct from p_service_id
         or v_booking.slot_time is distinct from p_slot_time
         or v_booking.customer_name is distinct from v_name
         or v_booking.phone is distinct from v_phone then
        raise exception using errcode = '22023', message = 'REQUEST_MISMATCH';
      end if;
  end;

  return query select v_booking.id, v_booking.service_id, v_booking.customer_name,
    v_booking.phone, v_booking.slot_time, v_booking.end_time, v_booking.status;
end;
$$;
revoke all on function public.create_booking(uuid, uuid, timestamptz, text, text) from public, anon, authenticated;
grant execute on function public.create_booking(uuid, uuid, timestamptz, text, text) to anon, authenticated;

-- Source: supabase/migrations/20261005020000_add_admin_dashboard.sql
-- Only the database owner provisions admins, using an existing auth.users ID.
-- Password/email authentication or editable user_metadata is not authorization.
create table private.salon_admins (
  user_id uuid primary key references auth.users (id) on delete cascade
);
alter table private.salon_admins enable row level security;
revoke all on table private.salon_admins from public, anon, authenticated;

comment on table private.salon_admins is
  'Owner-managed admin allowlist. Manually insert an existing auth.users ID; never expose provisioning to API roles or infer it from user_metadata.';

create function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from private.salon_admins as admin
    where admin.user_id = (select auth.uid())
  );
$$;
revoke all on function public.is_admin() from public, anon, authenticated;
grant execute on function public.is_admin() to authenticated;

-- Validated constraints intentionally abort for incompatible existing rows.
-- No customer data or services are silently rewritten or removed.
alter table public.services add constraint services_name_admin_bounds
  check (pg_catalog.char_length(pg_catalog.btrim(name)) between 1 and 120
    and name !~ '[[:cntrl:]]');
alter table public.services add constraint services_duration_admin_bounds
  check (duration between 1 and 600);
alter table public.services add constraint services_price_admin_bounds
  check (price <= 99999999.99);
-- The original numeric(10,2), nonnegative, and no-NaN constraints remain.

revoke all on table public.services from public, anon, authenticated;
grant select on table public.services to anon, authenticated;
-- Column privileges exclude id, even for allowlisted administrators.
grant insert (name, duration, price), update (name, duration, price)
  on table public.services to authenticated;
grant delete on table public.services to authenticated;

-- Retain the existing public service SELECT policy.
create policy "Admins can insert services"
  on public.services for insert to authenticated
  with check ((select public.is_admin()));
create policy "Admins can update services"
  on public.services for update to authenticated
  using ((select public.is_admin()))
  with check ((select public.is_admin()));
create policy "Admins can delete services"
  on public.services for delete to authenticated
  using ((select public.is_admin()));

revoke all on table public.bookings from public, anon, authenticated;
grant select on table public.bookings to authenticated;
create policy "Admins can read bookings"
  on public.bookings for select to authenticated
  using ((select public.is_admin()));
-- No direct client booking write privileges or write policies. The guest RPC
-- remains available; admin status changes go through the locked RPC below.

create function public.list_admin_bookings(
  p_view text,
  p_offset integer default 0,
  p_limit integer default 51
)
returns table (
  id uuid,
  customer_name text,
  phone text,
  service_id uuid,
  service_name text,
  slot_time timestamptz,
  end_time timestamptz,
  status public.booking_status
)
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_time_zone text;
  v_today date;
  v_today_start timestamp;
  v_tomorrow_start timestamp;
begin
  -- Gate before validating input or inspecting any booking/customer data.
  if not public.is_admin() then
    raise exception using errcode = '42501', message = 'ADMIN_REQUIRED';
  end if;
  if p_view is null or p_view not in ('today', 'upcoming')
     or p_offset is null or p_offset not between 0 and 10000
     or p_limit is null or p_limit not between 1 and 51 then
    raise exception using errcode = '22023', message = 'INVALID_ADMIN_BOOKING_INPUT';
  end if;

  select settings.time_zone into strict v_time_zone
  from private.salon_booking_settings as settings where settings.singleton;
  v_today := (pg_catalog.statement_timestamp() at time zone v_time_zone)::date;
  -- Compare salon wall times to local midnights, not a fixed 24-hour instant
  -- range. This also includes BOTH occurrences of a repeated midnight (e.g.
  -- America/Havana); converting an ambiguous midnight to one instant would
  -- silently exclude the earlier occurrence on a DST fallback day.
  v_today_start := v_today::timestamp;
  v_tomorrow_start := (v_today + 1)::timestamp;

  return query
  select booking.id, booking.customer_name, booking.phone, booking.service_id,
         service.name, booking.slot_time, booking.end_time, booking.status
  from public.bookings as booking
  join public.services as service on service.id = booking.service_id
  where (p_view = 'today'
           and (booking.slot_time at time zone v_time_zone) >= v_today_start
           and (booking.slot_time at time zone v_time_zone) < v_tomorrow_start)
     or (p_view = 'upcoming'
           and (booking.slot_time at time zone v_time_zone) >= v_tomorrow_start)
  order by booking.slot_time, booking.id
  limit p_limit offset p_offset;
end;
$$;
revoke all on function public.list_admin_bookings(text, integer, integer) from public, anon, authenticated;
grant execute on function public.list_admin_bookings(text, integer, integer) to authenticated;

create function public.admin_set_booking_status(
  p_booking_id uuid,
  p_status public.booking_status
)
returns table (
  id uuid,
  customer_name text,
  phone text,
  service_id uuid,
  slot_time timestamptz,
  end_time timestamptz,
  status public.booking_status
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_booking public.bookings%rowtype;
begin
  if not public.is_admin() then
    raise exception using errcode = '42501', message = 'ADMIN_REQUIRED';
  end if;
  if p_booking_id is null then
    raise exception using errcode = '22023', message = 'INVALID_BOOKING_INPUT';
  end if;
  if p_status is null or p_status not in ('confirmed', 'cancelled') then
    raise exception using errcode = '22023', message = 'INVALID_BOOKING_STATUS';
  end if;

  -- Serialize changes to this row so a concurrent cancellation cannot reopen it.
  select booking.* into v_booking
  from public.bookings as booking where booking.id = p_booking_id for update;
  if not found then
    raise exception using errcode = '22023', message = 'BOOKING_NOT_FOUND';
  end if;

  if v_booking.status is distinct from p_status then
    if v_booking.status not in ('pending', 'confirmed') then
      raise exception using errcode = '22023', message = 'BOOKING_STATUS_FINAL';
    end if;
    update public.bookings as booking set status = p_status
    where booking.id = v_booking.id returning booking.* into v_booking;
  end if;
  -- Exact confirmed/cancelled retries return the unchanged receipt.
  return query select v_booking.id, v_booking.customer_name, v_booking.phone,
    v_booking.service_id, v_booking.slot_time, v_booking.end_time, v_booking.status;
end;
$$;
revoke all on function public.admin_set_booking_status(uuid, public.booking_status) from public, anon, authenticated;
grant execute on function public.admin_set_booking_status(uuid, public.booking_status) to authenticated;

-- Source: supabase/migrations/20261005030000_allow_public_booking_inserts.sql
-- Preserve admin-only SELECT and existing RPCs; expose only the columns a
-- customer needs to submit an appointment request. IDs/status/end times are
-- database-owned. No anonymous booking SELECT or client UPDATE/DELETE grants.
revoke insert on table public.bookings from public, anon, authenticated;
revoke insert (id, customer_name, phone, service_id, slot_time, end_time, status)
  on table public.bookings from public, anon, authenticated;
grant insert (customer_name, phone, service_id, slot_time)
  on table public.bookings to anon, authenticated;

create policy "Public can submit bookings"
  on public.bookings
  for insert
  to anon, authenticated
  with check (status = 'pending'::public.booking_status);

-- Direct inserts must not bypass the RPC's schedule/contact checks. Definer
-- access is needed to read private salon settings without granting their use
-- to customers. Invocation remains trigger-only, with a fixed search path.
create function private.validate_public_booking_insert()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_role text := coalesce(nullif(pg_catalog.current_setting('role', true), 'none'), session_user::text);
  v_time_zone text;
  v_today date;
  v_local_start timestamp;
  v_duration integer;
  v_now timestamptz;
begin
  -- Owner/service-role maintenance remains possible (e.g. importing historic
  -- bookings). SECURITY DEFINER RPCs keep the original SET ROLE value, so their
  -- API-origin inserts are checked here as well. No user-supplied metadata or
  -- request claim is used to decide whether validation is required.
  if v_role not in ('anon', 'authenticated') then
    return new;
  end if;

  new.customer_name := pg_catalog.btrim(new.customer_name);
  new.phone := pg_catalog.btrim(new.phone);
  if new.service_id is null or new.slot_time is null
     or not pg_catalog.isfinite(new.slot_time)
     or new.customer_name is null
     or pg_catalog.char_length(new.customer_name) not between 2 and 100
     or new.customer_name ~ '[[:cntrl:]]'
     or new.phone is null or pg_catalog.char_length(new.phone) > 32
     or new.phone !~ '^[0-9+(). -]+$'
     or pg_catalog.char_length(pg_catalog.regexp_replace(new.phone, '[^0-9]', '', 'g')) not between 7 and 15
     or new.status not in ('pending', 'confirmed') then
    raise exception using errcode = '22023', message = 'INVALID_BOOKING_INPUT';
  end if;

  select settings.time_zone into strict v_time_zone
  from private.salon_booking_settings as settings where settings.singleton for share;
  select service.duration into v_duration
  from public.services as service where service.id = new.service_id for share;
  if not found then
    raise exception using errcode = '22023', message = 'INVALID_SERVICE';
  end if;

  -- BEFORE triggers run in name order. The duration trigger already ran; derive
  -- again while holding the service lock to prevent a concurrent duration edit
  -- from shortening the interval the customer actually reserves.
  new.end_time := new.slot_time + pg_catalog.make_interval(mins => v_duration);
  v_now := pg_catalog.clock_timestamp();
  v_today := (v_now at time zone v_time_zone)::date;
  v_local_start := new.slot_time at time zone v_time_zone;
  if new.slot_time <= v_now then
    raise exception using errcode = '23P01', message = 'SLOT_UNAVAILABLE';
  end if;
  if v_local_start::date < v_today or v_local_start::date > v_today + 90
     or v_local_start::time < time '10:00' or v_local_start::time > time '19:30'
     or extract(minute from v_local_start) not in (0, 30)
     or extract(second from v_local_start) <> 0
     or (v_local_start at time zone v_time_zone) <> new.slot_time
     or new.end_time > (v_local_start::date + time '20:00') at time zone v_time_zone then
    raise exception using errcode = '22023', message = 'INVALID_BOOKING_INPUT';
  end if;

  -- Existing bookings_no_overlap is the race-safe enforcement layer for both
  -- direct inserts and RPC reservations; don't expose private rows to check it.
  return new;
end;
$$;
revoke all on function private.validate_public_booking_insert() from public, anon, authenticated;

create trigger bookings_validate_public_insert
before insert on public.bookings
for each row execute function private.validate_public_booking_insert();

comment on policy "Public can submit bookings" on public.bookings is
  'Guests and ordinary authenticated users can submit pending requests using customer fields only. Customer records remain admin-readable only.';

-- Source: supabase/migrations/20261005040000_validate_raw_service_values.sql
-- numeric(10,2) rounds before CHECK constraints see the input: 1.239 becomes
-- 1.24 and -0.001 becomes 0.00. Remove the typemod, not the monetary limits.
-- Existing prices retain their exact values; no service prices are rewritten.
alter table public.services alter column price type numeric using price::numeric;
alter table public.services
  drop constraint services_price_nonnegative,
  add constraint services_price_nonnegative
    check (price >= 0 and price not in ('NaN'::numeric, 'Infinity'::numeric, '-Infinity'::numeric)),
  add constraint services_price_two_decimals
    check (price = pg_catalog.trunc(price, 2));
-- services_price_admin_bounds still enforces the inclusive 99999999.99 maximum.
-- All CHECK constraints are validated, including against existing rows. Extra
-- trailing zeroes (e.g. 1.2300) represent a valid two-decimal monetary value.
comment on column public.services.price is
  'Finite nonnegative amount in the salon currency, not cents; at most two decimal places in value, maximum 99999999.99. Raw fractional cents are rejected, not rounded.';

-- This helper uses only NEW and schema-qualified builtins. It neither reads
-- private data nor elevates the writer's privileges; existing RLS/grants stay.
create function private.normalize_service_name()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.name := pg_catalog.btrim(new.name);
  return new;
end;
$$;
revoke all on function private.normalize_service_name() from public, anon, authenticated;

create trigger services_normalize_name
before insert or update on public.services
for each row execute function private.normalize_service_name();

-- Deliberately normalize existing outer space padding, including padding that
-- the old trimmed-length check allowed to exceed 120 stored characters. Keep
-- internal spaces, IDs, durations, prices and booking snapshots unchanged.
update public.services set name = pg_catalog.btrim(name)
where name is distinct from pg_catalog.btrim(name);

alter table public.services
  drop constraint services_name_admin_bounds,
  add constraint services_name_admin_bounds
    check (pg_catalog.char_length(name) between 1 and 120
      and name = pg_catalog.btrim(name)
      and name !~ '[[:cntrl:]]');
-- btrim removes outer spaces, not controls: tabs/newlines still fail the CHECK.
-- Bound the actual stored name, not merely a trimmed projection of it.
comment on column public.services.name is
  'Outer spaces are trimmed on insert/update. Stored names contain 1-120 characters and no control characters; internal spaces are preserved.';

commit;
